import { strict as assert } from "node:assert";
import { normalizeOutputType } from "./normalize-output-type";

const cases: Record<string, string> = {
  synthesis: "research",
  report: "document",
  researchReport: "research",
  "Research Report": "research",
  research_summary: "research",
  summary_report: "summary",
  analysis: "research",
  writeup: "markdown",
  article: "markdown",
  presentation: "slides",
  deck: "slides",
  pdf: "document",
  doc: "document",
  text: "markdown",
  notes: "markdown",
  citations: "research",
  citation: "research",
  sources: "research",
  references: "research",
  bibliography: "research",
  investigation: "research",
  findings: "research",
  essay: "markdown",
  powerpoint: "slides",
  overview: "summary",
  "executive summary": "summary",
  recap: "summary",
  attachment: "file",
  download: "file",
  archive: "file",
  synthesized: "research",
  "source citations": "research",
  "executive summary report": "summary",
  "quarterly findings": "research",
  "final pdf report": "document",
};
for (const [input, expected] of Object.entries(cases)) assert.equal(normalizeOutputType(input), expected, input);
