"use client";

import Link from "next/link";
import { ArrowLeft, FileText, RefreshCw } from "lucide-react";

import { MissionArtifactViewer } from "@/components/missions/mission-artifact-viewer";
import { MissionLauncher } from "@/components/missions/mission-launcher";
import { useMission } from "@/lib/mission-polling";
import type { Mission, MissionLog, MissionStatus } from "@/types/mission";

interface MissionWorkspaceProps { missionId: string; }

const statusLabel: Record<MissionStatus, string> = { queued: "Queued", planning: "Planning", researching: "Researching", executing: "Running", reviewing: "Reviewing", completed: "Completed", failed: "Failed" };
const statusColor: Record<MissionStatus, string> = { queued: "#9299a8", planning: "#c8a46b", researching: "#8db7ff", executing: "#ae9cff", reviewing: "#e5b978", completed: "#6ed9a4", failed: "#ff7979" };

export function MissionWorkspace({ missionId }: MissionWorkspaceProps): React.ReactElement {
  const { mission, error } = useMission(missionId);
  if (error) return <WorkspaceError message={error} />;
  if (!mission) return <div className="content"><div className="eyebrow">Mission workspace</div><h1>Loading mission state…</h1><p className="dim">Waiting for the existing mission API.</p></div>;
  const agents = deriveAgents(mission);
  const events = deriveEvents(mission);
  const current = mission.logs.at(-1);
  const displayStatus = current?.metadata.toolId === "browser" && mission.status === "executing" ? "Browsing" : current?.metadata.agent === "document" && mission.status === "executing" ? "Generating documents" : statusLabel[mission.status];

  return <main className="workspace">
    <aside className="rail"><Link href="/missions" className="brand">After<span>You</span></Link><div><div className="eyebrow">Mission</div><p className="mission-name">{mission.title}</p></div><div className="mobile-facts"><span className="status-pill" style={{ "--status": statusColor[mission.status] } as React.CSSProperties}>{displayStatus}</span><span className="dim">{mission.progress}%</span></div><div className="facts"><div className="fact"><span className="fact-label">Progress</span><span className="fact-value">{mission.progress}%</span><div className="progress-track"><i style={{ width: `${mission.progress}%` }} /></div></div><div className="fact"><span className="fact-label">Current stage</span><span className="fact-value">{current?.action ?? displayStatus}</span></div><div className="fact"><span className="fact-label">Estimated completion</span><span className="fact-value">{estimateCompletion(mission)}</span></div><div className="fact"><span className="fact-label">Artifacts</span><span className="fact-value">{mission.artifacts.length} generated</span></div></div><div><div className="eyebrow">Active agents</div><div className="agent-list" style={{ marginTop: 11 }}>{agents.length ? agents.map((agent) => <div className="agent-row" key={agent.id}><strong>{agent.name}</strong> · {agent.state}</div>) : <div className="agent-row">Agents will appear when the runtime starts.</div>}</div></div></aside>
    <section className="content"><header className="topbar"><div><Link href="/missions" className="eyebrow" style={{ textDecoration: "none" }}><ArrowLeft size={12} style={{ verticalAlign: "-2px" }} /> All missions</Link><h1>{mission.title}</h1><p>{mission.goal}</p></div><span className="status-pill" style={{ "--status": statusColor[mission.status] } as React.CSSProperties}>{displayStatus}</span></header><section className="section"><div className="section-header"><h2>Live timeline</h2><span className="eyebrow"><RefreshCw size={11} style={{ verticalAlign: "-2px" }} /> Polling every 2.5s</span></div><div className="timeline">{events.length ? events.map((event) => <TimelineCard key={event.id} event={event} />) : <div className="empty">No runtime events have been recorded yet.</div>}</div></section><section className="section"><div className="section-header"><h2>Agent activity</h2><span className="eyebrow">From structured logs</span></div><div className="agent-grid">{agents.length ? agents.map((agent) => <article className="agent-card" key={agent.id}><h3>{agent.name}</h3><p>{agent.currentTask}</p><div className="agent-stats"><span>Status<strong>{agent.state}</strong></span><span>Duration<strong>{agent.duration}</strong></span><span>Tools<strong>{agent.tools || "—"}</strong></span><span>Completed<strong>{agent.completedTasks}</strong></span></div></article>) : <div className="empty">Running agents will be shown here using real agent log entries.</div>}</div></section></section>
    <aside className="rail right-rail"><section><h2 className="panel-title">Artifacts</h2><div className="artifact-list">{mission.artifacts.length ? mission.artifacts.map((artifact) => <article className="artifact-card" key={artifact.id}><h3>{artifact.name}</h3><p>{artifact.mimeType ?? artifact.kind}</p><MissionArtifactViewer missionId={mission.id} artifact={artifact} /></article>) : <div className="empty">Generated files will appear here.</div>}</div></section><section><h2 className="panel-title">Outputs</h2><div className="output-list">{mission.outputs.length ? mission.outputs.map((output) => <article className="output-card" key={output.id}><h3><FileText size={13} style={{ verticalAlign: "-2px", marginRight: 5 }} />{output.title}</h3><p>{output.type} · {new Date(output.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p><div className="preview"><pre>{output.content}</pre></div></article>) : <div className="empty">Mission outputs will appear here.</div>}</div></section></aside>
  </main>;
}

function WorkspaceError({ message }: { message: string }): React.ReactElement { return <main className="content"><div className="eyebrow">Mission workspace</div><h1>We couldn’t load this mission.</h1><p className="dim">{message}</p><div style={{ marginTop: 20 }}><MissionLauncher /></div></main>; }

function TimelineCard({ event }: { event: WorkspaceEvent }): React.ReactElement { return <article className="event-card"><div className="event-summary"><span className="event-time">{new Date(event.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</span><span className="event-title">{event.title}</span></div>{event.meta && <p className="event-meta">{event.meta}</p>}{event.details && <details><summary>View details</summary><pre className="detail-json">{JSON.stringify(event.details, null, 2)}</pre></details>}</article>; }

interface WorkspaceEvent { id: string; timestamp: string; title: string; meta?: string; details?: Record<string, unknown>; }
function deriveEvents(mission: Mission): WorkspaceEvent[] { return [...mission.timeline.map((event) => ({ id: event.id, timestamp: event.timestamp, title: event.label, meta: event.detail })), ...mission.logs.map((log) => ({ id: log.id, timestamp: log.timestamp, title: log.action, meta: eventMeta(log), details: log.metadata }))].sort((a, b) => a.timestamp.localeCompare(b.timestamp)); }
function eventMeta(log: MissionLog): string | undefined { const agent = typeof log.metadata.agent === "string" ? agentName(log.metadata.agent) : undefined; const tool = typeof log.metadata.toolId === "string" ? `${log.metadata.toolId} tool` : undefined; const duration = typeof log.metadata.executionTimeMs === "number" ? `${log.metadata.executionTimeMs}ms` : undefined; return [agent, tool, duration].filter(Boolean).join(" · ") || undefined; }
function agentName(id: string): string { return ({ planner: "Planner", research: "Research", browser: "Browser", coding: "Coding", document: "Document", reviewer: "Reviewer" } as Record<string, string>)[id] ?? id; }
function deriveAgents(mission: Mission): Array<{ id: string; name: string; state: string; currentTask: string; tools: string; completedTasks: number; duration: string }> { const grouped = new Map<string, MissionLog[]>(); for (const log of mission.logs) { const agent = log.metadata.agent; if (typeof agent === "string") grouped.set(agent, [...(grouped.get(agent) ?? []), log]); } return [...grouped].map(([id, logs]) => { const latest = logs.at(-1)!; const started = logs[0]!; const tools = [...new Set(logs.map((log) => log.metadata.toolId).filter((tool): tool is string => typeof tool === "string"))].join(", "); return { id, name: agentName(id), state: latest.status === "failed" ? "Failed" : mission.status === "completed" ? "Complete" : latest.status === "succeeded" ? "Ready" : "Working", currentTask: latest.action, tools, completedTasks: logs.filter((log) => log.status === "succeeded").length, duration: formatDuration(new Date(latest.timestamp).getTime() - new Date(started.timestamp).getTime()) }; }); }
function formatDuration(value: number): string { if (value < 1_000) return "<1s"; if (value < 60_000) return `${Math.round(value / 1_000)}s`; return `${Math.floor(value / 60_000)}m`; }
function estimateCompletion(mission: Mission): string { if (mission.status === "completed") return "Complete"; if (mission.status === "failed") return "Needs attention"; const elapsed = (Date.now() - new Date(mission.createdAt).getTime()) / 60_000; const remaining = Math.max(0, mission.estimatedDuration * (1 - mission.progress / 100) - elapsed); return remaining < 1 ? "Less than a minute" : `About ${Math.ceil(remaining)} min`; }
