import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { jsonError } from "@/lib/http";
export const runtime = "nodejs";
const schema = z.object({ workspacePath: z.string().min(1).max(4096) });
const ignored = (name: string) => ["node_modules", ".git", "dist", "build", "artifacts"].includes(name) || name.startsWith(".next");
async function index(root: string, deadline: number, depth = 0, entries: string[] = [], extensions = new Set<string>()): Promise<{ entries: string[]; extensions: Set<string>; files: number; partial: boolean }> { let files = 0; let partial = false; if (Date.now() > deadline || depth > 3) return { entries, extensions, files, partial: true }; let children; try { children = await readdir(root, { withFileTypes: true }); } catch { return { entries, extensions, files, partial: true }; } for (const child of children) { if (Date.now() > deadline) { partial = true; break; } if (child.isSymbolicLink() || ignored(child.name)) continue; const full = path.join(root, child.name); const relative = path.relative(root, full); if (child.isDirectory()) { entries.push(`${relative}/`); if (depth < 1 || /^(src|app|pages|components|public|lib)$/i.test(child.name)) { const next = await index(full, deadline, depth + 1); entries.push(...next.entries.map((entry) => path.join(child.name, entry))); next.extensions.forEach((extension) => extensions.add(extension)); files += next.files; partial ||= next.partial; } } else { files++; entries.push(relative); const extension = path.extname(child.name); if (extension) extensions.add(extension); } } return { entries, extensions, files, partial }; }
export async function POST(request: Request): Promise<Response> { try { const { workspacePath } = schema.parse(await request.json()); const root = path.resolve(workspacePath); if (!(await stat(root)).isDirectory()) throw new Error("Workspace path must be a folder"); const result = await index(root, Date.now() + 1200); const names = new Set(result.entries.map((entry) => entry.split(/[\\/]/)[0])); const configFiles = result.entries.filter((entry) => /(?:package\.json|next\.config|vite\.config|tsconfig|tailwind\.config|README)/i.test(entry)); const framework = names.has("app") || names.has("pages") ? "Next.js / React" : configFiles.some((file) => /vite/i.test(file)) ? "Vite" : configFiles.some((file) => /package\.json/i.test(file)) ? "JavaScript project" : "Local project"; return Response.json({ data: { workspaceName: path.basename(root), workspacePath: root, indexedAt: new Date().toISOString(), fileCount: result.files, directoryTree: result.entries.slice(0, 500), extensions: [...result.extensions].sort(), framework, configFiles, sourceFolders: [...names].filter((name) => /^(src|app|pages|components|public|lib)$/i.test(name)), partial: result.partial } }); } catch (error) { return jsonError(error); } }
